config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#index'
  get '/users', to: 'users#index'
  get '/users/search', to: 'users#search'
  get '/users/mark', to: 'users#mark'
  get '/users/chart', to: 'users#chart'
  resources :posts
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord

  # Rspec用のコード
  #attr_accessor :test_name, :test_age

  #def initialize(test_name:,test_age:)
   # @test_name = test_name
   # @test_age = test_age
  #end

  def disp_name
    if @test_age > 19
      return "#{@test_name}さん"
    elsif @test_age > 10
      return "#{@test_name}君"
    elsif @test_age > 0
      return "#{@test_name}ちゃん"
    else
      return "不正な値です。"
    end
  end

end

app/models/user_search.rb
class UserSearch
  include ActiveModel::Model

  attr_accessor :search_name, :search_age, :search_address

  def execute
    User.ransack(
      name_eq: @search_name, age_eq: @search_age, address_eq: @search_address
    )
      .result
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @greet = 'Welcome to Active-Admin-app'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    Post.create(post_params)
    # 投稿完了後、すぐに一覧表示画面へ遷移
    redirect_to :action => :index
  end

  private

  def post_params
    params.require(:post).permit(:image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def search
    user_search = UserSearch.new(params_user_search)
    @users = user_search.execute
  end

  def mark; end

  def chart
    gon.labels =  ["東京 ", "埼玉", "沖縄", "愛知", "千葉", "神奈川", "福岡"]
    gon.scores = [7.3, 2.8, 2.6, 2.4, 1.6, 1.5, 0.4]
  end

  private

  def params_user_search
    params.permit(:search_name, :search_age, :search_address)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  require 'redcarpet'
  require 'coderay'

  class HTMLwithCoderay < Redcarpet::Render::HTML
    def block_code(code, language)
      language = language.split(':')[0] if language.present?

      case language.to_s
      when 'rb'
        lang = :ruby
      when 'yml'
        lang = :yaml
      when 'css'
        lang = :css
      when 'html'
        lang = :html
      when ''
        lang = :md
      else
        lang = language
      end

      CodeRay.scan(code, lang).div
    end
  end

  def markdown(text)
    html_render =
      HTMLwithCoderay.new(
        filter_html: true,
        hard_wrap: true,
        link_attributes: { rel: 'nofollow', target: '_blank' }
      )
    options = {
      autolink: true,
      space_after_headers: true,
      no_intra_emphasis: true,
      fenced_code_blocks: true,
      tables: true,
      hard_wrap: true,
      xhtml: true,
      lax_html_blocks: true,
      strikethrough: true
    }
    markdown = Redcarpet::Markdown.new(html_render, options)
    markdown.render(text)
  end
end

app/views/homes/index.html.erb
<nav>
  <%= link_to "管理画面","/admin" %>
  <%= link_to "ユーザー一覧", "/users" %>
  <%= link_to "画像投稿画面", new_post_path %>
  <%= link_to "Markdown", "/users/mark" %>
  <%= link_to "都道府県別人口増減率（グラフ）", "/users/chart" %>
</nav>

<h1 class="greet">
  <%= @greet %>
</h1>

<footer>
  <small>© 2019　西原</small>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ActiveAdminSample</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= include_gon %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= yield %>
</body>
</html>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
<%= image_tag post.image_url(:thumb) %>
<% end %>

app/views/posts/new.html.erb
<%= form_for @post do |f| %>
<%= f.file_field :image %>
<%= f.submit %>
<% end %>

app/views/users/chart.html.erb
<h1>都道府県別人口増減率</h1>
<canvas id="myChart"></canvas>
<p>　※前年度比の人口増減率、上位7県を記載。<br>
  　<span style="color:red;font-weigth:bold;">※グラフが表示されていない時は、更新をクリック！</span>
</p>

app/views/users/index.html.erb
<h1>ユーザー一覧</h1>
<table>
  <tbody>
    <thead>
      <tr>
        <th>名前</th>
        <th>年齢</th>
        <th>住所</th>
      </tr>
    </thead>
    <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.age %></td>
      <td><%= user.address %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<div class="buttun_box">
  <button>
    <%= link_to "ユーザー情報検索へ" , "/users/search" %>
  </button>
</div>

app/views/users/mark.html.erb
<%
  text =<<~TEXT
    # 大見出し
    ## 中見出し
    ### 小見出し
    1. リスト
    2. リスト
    3. リスト
  TEXT
 %>
<%= markdown(text).html_safe %>

app/views/users/search.html.erb
<%= form_tag('/users/search', method: :get) do %>
<h1>ユーザー情報検索</h1>
<div class="search_box"><%= label_tag :名前 %>：
  <%= text_field_tag :search_name %></div class="search_box">
<div class="search_box"><%= label_tag :年齢 %>：
  <%= text_field_tag :search_age %></div class="search_box">
<div class="search_box"><%= label_tag :住所 %>：
  <%= text_field_tag :search_address %></div class="search_box">
<div class="search_box"><%= submit_tag '検索' %></div class="search_box">
<% end %>
<table>
  <tbody>
    <thead>
      <tr>
        <th>名前</th>
        <th>年齢</th>
        <th>住所</th>
      </tr>
    </thead>
    <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.age %></td>
      <td><%= user.address %></td>
    </tr>
    <% end %>
  </tbody>
</table>